wiggum/authorization/urls.py
from django.conf.urls import patterns, url

from .views import (LoginView, JWTTesView, ResetPasswordView,
                    RecoverPasswordView, CloneCookieView, LogoutView,
                    ImpersonateView, SFAView)

urlpatterns = patterns('',
    url(r'^login/$',
        LoginView.as_view(),
        name='login'),

    url(r'^reset-password/(?P<user_id>[0-9]+)/(?P<uuid>[0-9a-zA-Z\-]{36})$',
        ResetPasswordView.as_view(),
        name='reset-password'),

    url(r'^recover-password$',
        RecoverPasswordView.as_view(),
        name='recover-password'),

    url(r'^test/jwt$',
        JWTTesView.as_view(),
        name='test-jwt'),

    url(r'^clone/(?P<token>[a-zA-Z0-9\-\_\.]+)$',
        CloneCookieView.as_view(),
        name='clone-cookie'),

    url(r'^logout/$',
        LogoutView.as_view(),
        name='logout'),

    url(r'^impersonate/(?P<user_id>[0-9]+)$',
        ImpersonateView.as_view(),
        name='impersonate'),

    url(r'^sfa/(?P<user_id>[0-9]+)/(?P<uuid>[0-9a-zA-Z\-]{36})$',
        SFAView.as_view(),
        name='sfa'),
)

wiggum/wiggum/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import TemplateView

from . import apiv1
from administrator import admin
from authorization import urls as auth_urls


api_url = "^api/{version}/".format(version=settings.API_VERSION)

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^a/', include(auth_urls, namespace='auth')),
    url(api_url, include(apiv1.urlpatterns, namespace='api')),
    url(r'^easter-egg/', TemplateView.as_view(template_name='easter-egg.html'), name='easter-egg'),
    url(r'^unauthorized/', TemplateView.as_view(template_name='unauthorized.html'), name='unauthorized'),
    url(r'^admin/', include(admin.urls)),

    # Swagger docs for the api
    url(r'^docs/', include('rest_framework_swagger.urls')),

    # Prometheus urls
    url('', include('django_prometheus.urls')),

    # Robots.txt
    url(r'^robots.txt$', TemplateView.as_view(
        template_name="robots.txt",
        content_type="text/plain"), name='unauthorized'),
]

# 404 and 505 templates
handler404 = 'wiggum.views.handler404'
handler505 = 'wiggum.views.handler505'

wiggum/wiggum/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext


def handler404(request):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('500.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response

wiggum/wiggum/templates/base.html
{# base.html #}
{% load pipeline %}
{% load i18n %}
{% load static %}

<html>
  <head>
    <title>{% block title %} {% trans 'Client access' %} {% endblock %}</title>
    <link rel="shortcut icon" href="{% static "img/favicon.png" %}" type="image/x-icon">
    {% stylesheet 'default' %}
    {% stylesheet 'wiggum' %}
    {% javascript 'default' %}

    <!-- muahahaha! -->
    {% javascript 'easter-egg' %}

    {% block head %}
    {% endblock head %}

  </head>

  <body>
  {% block content %}
  {% endblock content %}
  {% block footer%}
  {% endblock footer %}
  </body>

</html>

wiggum/wiggum/templates/easter-egg.html
{% load i18n %}
{% load pipeline %}
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<title>{% trans "You shouldn't be here ¬¬" %}</title>
        <style type="text/css">
          body {

            background-color: #000;
          }
          @font-face {
    	    font-family: 'BDCartoonShoutRegular';
            src: url('{% static "fonts/BD_Cartoon_Shout-webfont.ttf" %}') format('truetype');
    	    font-weight: normal;
    	    font-style: normal;
          }
          #pacman {
            height:450px;
            width:342px;
            margin:20px auto;
          }
        <style>

        </style>
	</head>
	<body>
        <div id="pacman"></div>
        {% javascript 'modernizr' %}
        <script type="text/javascript" src="{% static "js/pacman.js" %}" charset="utf-8"></script>
        <script>

          var el = document.getElementById("pacman");

          if (Modernizr.canvas && Modernizr.localstorage &&
              Modernizr.audio && (Modernizr.audio.ogg || Modernizr.audio.mp3)) {
              window.setTimeout(function () { PACMAN.init(el, "{% static "" %}"); }, 0);
          } else {
            el.innerHTML = "Sorry, needs a decent browser<br /><small>" +
              "(firefox 3.6+, Chrome 4+, Opera 10+ and Safari 4+)</small>";
          }
        </script>

    </body>
</html>

wiggum/wiggum/templates/error.html
{% load i18n %}
{% load pipeline %}

<!DOCTYPE html>
<html>
	<head>
        <!-- muahahaha! -->
        {% javascript 'default' %}
        {% javascript 'easter-egg' %}
		{% stylesheet 'error' %}
		<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Oswald">
        <title>{% block title %}{% endblock title %}</title>
	</head>
	<body>
		<div class="error-container">
			<h1 class="code-title">{% block error-code %}{% endblock error-code %}</h1>
			<div class="error-message">
				<h2 class="error-title">{% block error-title %}{% endblock error-title %}</h2>
				<p class="error-text">{% block error-text %}{% endblock error-text %}</p>
			</div>
		</div>
	</body>
</html>

wiggum/wiggum/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="index-block-header">
  <div class="container">
    <i class="fa fa-shield logo"></i>
    <h1>Welcome to wiggum</h1>
    <p class="lead">
      Keep all your applications authentication and authorization centraliced and secure.</br>
      Use the latest standards to authenticate your users
    </p>
  </div><!-- /.container -->
</div>
<div class="index-block">
  <div class="container">
      <div class="row">
        <div class="col-md-3 index-block-column">
          <div class="centered-icon">
            <i class="fa fa-cog fa-5x"></i>
          </div>
          <p>Check out the admin page where you can manage all your applications users and permissions</p>
          <p><a class="btn btn-default" href="{% url 'admin:index'%}" role="button">View details »</a></p>
        </div>
        <div class="col-md-3 index-block-column">
          <div class="centered-icon">
            <i class="fa fa-send fa-5x"></i>
          </div>
          <p>Watch your REST api endpoints and get information about what fields you need to pass or ask for.</br>
          Take into account that you will need access to this. Use the Authorization header in the form of: "Bearer {TOKEN}"
          </p>
          <p><a class="btn btn-default" href="{% url 'api:api-root'%}" role="button">View details »</a></p>
       </div>
        <div class="col-md-3 index-block-column">
          <div class="centered-icon">
            <i class="fa fa-lock fa-5x"></i>
          </div>
          <p>Login into the application to gain access to a whole new wolrd of applications. Login once and access all</p>
          <p><a class="btn btn-default" href="{% url 'auth:login'%}" role="button">View details »</a></p>
        </div>
        <div class="col-md-3 index-block-column">
          <div class="centered-icon">
            <i class="fa fa-asterisk fa-5x"></i>
          </div>
          <p>Test your jwt cookie with this simple utility and know if you are signed correctly in all the applications supported by wiggum</p>
          <p><a class="btn btn-default" href="{% url 'auth:test-jwt'%}" role="button">View details »</a></p>
        </div>
      </div>
  </div><!-- /.container -->
</div>

{% endblock content %}
{% block footer %}
    <!-- Footer
================================================== -->
<footer class="bs-docs-footer" role="contentinfo">
</footer>
{% endblock footer %}

wiggum/wiggum/templates/unauthorized.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
<style>
	.index-block-header {
	    padding: 40px 15px;
	    background-color: #5e0303;
	    color: #eae3e3;
	    text-align: center;
	}

	.logo {
	  color: #eae3e3;
	  font-size: 15em;
	}
</style>
{% endblock head %}

{% block content %}

<div class="index-block-header">
  <div class="container">
	<i class="fa fa-ban logo"></i>
    <h1>Unathorized</h1>
    <p class="lead">
      You dont have access to the requested URL.</br>
      Please <a href="{% url "auth:logout" %}">logout</a> and <a src="{% url "auth:login" %}">login</a> again.
    </p>
  </div><!-- /.container -->
</div>
{% endblock content %}
{% block footer %}
    <!-- Footer
================================================== -->
<footer class="bs-docs-footer" role="contentinfo">
</footer>
{% endblock footer %}