wiggum/authorization/urls.py
from django.conf.urls import patterns, url

from .views import (LoginView, JWTTesView, ResetPasswordView,
                    RecoverPasswordView, CloneCookieView, LogoutView,
                    ImpersonateView, SFAView)

urlpatterns = patterns('',
    url(r'^login/$',
        LoginView.as_view(),
        name='login'),

    url(r'^reset-password/(?P<user_id>[0-9]+)/(?P<uuid>[0-9a-zA-Z\-]{36})$',
        ResetPasswordView.as_view(),
        name='reset-password'),

    url(r'^recover-password$',
        RecoverPasswordView.as_view(),
        name='recover-password'),

    url(r'^test/jwt$',
        JWTTesView.as_view(),
        name='test-jwt'),

    url(r'^clone/(?P<token>[a-zA-Z0-9\-\_\.]+)$',
        CloneCookieView.as_view(),
        name='clone-cookie'),

    url(r'^logout/$',
        LogoutView.as_view(),
        name='logout'),

    url(r'^impersonate/(?P<user_id>[0-9]+)$',
        ImpersonateView.as_view(),
        name='impersonate'),

    url(r'^sfa/(?P<user_id>[0-9]+)/(?P<uuid>[0-9a-zA-Z\-]{36})$',
        SFAView.as_view(),
        name='sfa'),
)

wiggum/wiggum/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import TemplateView

from . import apiv1
from administrator import admin
from authorization import urls as auth_urls


api_url = "^api/{version}/".format(version=settings.API_VERSION)

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^a/', include(auth_urls, namespace='auth')),
    url(api_url, include(apiv1.urlpatterns, namespace='api')),
    url(r'^easter-egg/', TemplateView.as_view(template_name='easter-egg.html'), name='easter-egg'),
    url(r'^unauthorized/', TemplateView.as_view(template_name='unauthorized.html'), name='unauthorized'),
    url(r'^admin/', include(admin.urls)),

    # Swagger docs for the api
    url(r'^docs/', include('rest_framework_swagger.urls')),

    # Prometheus urls
    url('', include('django_prometheus.urls')),

    # Robots.txt
    url(r'^robots.txt$', TemplateView.as_view(
        template_name="robots.txt",
        content_type="text/plain"), name='unauthorized'),
]

# 404 and 505 templates
handler404 = 'wiggum.views.handler404'
handler505 = 'wiggum.views.handler505'

wiggum/authorization/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


def get_redirect_uri(cleaned_data):
    uri = cleaned_data['redirect_uri']
    if uri and uri != str(None):
        return cleaned_data['redirect_uri']


class LoginForm(forms.Form):
    username_or_email = forms.CharField(label=_("Username or email"),
                                        required=True)
    password = forms.CharField(label=_("Password"),
                               required=True, widget=forms.PasswordInput)
    redirect_uri = forms.CharField(label=_("Redirection uri"),
                                   required=False, widget=forms.HiddenInput())

    def get_redirect_uri(self):
        return get_redirect_uri(self.cleaned_data)


class RecoverPasswordForm(forms.Form):
    email = forms.EmailField(label=_("Email"), required=True)
    redirect_uri = forms.CharField(label=_("Redirection uri"),
                                   required=False, widget=forms.HiddenInput())

    def get_redirect_uri(self):
        return get_redirect_uri(self.cleaned_data)

    error_messages = {
        'not_valid_email': _("The email is not valid"),
    }

# Don't check, this will be checked by the actions (check RECOVER_PASS_REQUEST_ACTIONS)
#    def clean_email(self):
#        email = self.cleaned_data.get("email")
#
#        if not User.objects.filter(email=email).exists():
#            raise forms.ValidationError(
#                self.error_messages['not_valid_email'],
#                code='not_valid_email',
#            )
#
#        return email


class ResetPasswordForm(forms.Form):
    password = forms.CharField(label=_("Password"), required=True,
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password validation"), required=True,
                                widget=forms.PasswordInput)

    redirect_uri = forms.CharField(label=_("Redirection uri"),
                                   required=False, widget=forms.HiddenInput())

    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }

    def get_redirect_uri(self):
        return get_redirect_uri(self.cleaned_data)


    def clean_password2(self):
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

wiggum/authorization/views.py
import uuid
import logging
import re
import urllib.parse

from django.conf import settings
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.core.validators import URLValidator
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.views.generic.edit import FormView
from django.views.generic import TemplateView, RedirectView

from themes.mixins import DynamicTemplateMixin
from users.models import User
from .actions import WiggumActionContext
from .forms import LoginForm, ResetPasswordForm, RecoverPasswordForm
from .utils import str_to_class, create_next_domains_url, get_redirect_url
from . import jwt_utils


logger = logging.getLogger(__name__)


class LoginView(DynamicTemplateMixin, FormView):
    template_name = 'authorization/login.html'
    form_class = LoginForm

    # Default  success
    success_url = settings.LOGIN_SUCCESS_REDIRECT

    # Actions
    pre_check_actions = settings.LOGIN_PRE_CHECK
    success_actions = settings.LOGIN_SUCCESS_ACTIONS
    failure_actions = settings.LOGIN_FAILURE_ACTIONS
    auth_backends = settings.WIGGUM_AUTHENTICATION_BACKENDS

    # Handy information
    user_authenticated = False
    jwt_token = None

    def get_login_pre_check_actions(self):
        return [str_to_class(action)() for action in self.pre_check_actions]

    def get_login_success_actions(self):
        return [str_to_class(action)() for action in self.success_actions]

    def get_login_failure_actions(self):
        return [str_to_class(action)() for action in self.failure_actions]

    def get_authentication_backends(self):
        return [str_to_class(backend)() for backend in self.auth_backends]

    def get(self, request, *args, **kwargs):
        """ Check if there is authenticated already before showing him the
            authentication form
        """
        response = super().get(request, *args, **kwargs)
        extra_context = {
            'redirect_url': self.get_success_url()
        }
        # Start actions
        action_context = WiggumActionContext(request, response, extra_context)
        for action in self.get_login_pre_check_actions():
            action_context = action.do(action_context, self)
            if action_context.break_chain:  # no more action chain to process
                break

        return action_context.response

    def form_valid(self, form):
        # neccessary data to pass to the backends
        credential_data = {
            'username': form.cleaned_data['username_or_email'],
            'password': form.cleaned_data['password'],
            'request': self.request, }

        # Check if user authenticates one backend at a time
        actions_context = {}
        backends = self.get_authentication_backends()
        for i in backends:
            user_authenticated = i.authenticate(**credential_data)
            if user_authenticated:
                actions_context['user_authenticated'] = True
                break

        # If not none then the user is authenticated
        if user_authenticated:
            logger.info("User {0} authenticated".format(user_authenticated))
            # Redirect to asked url if present, if not, default
            if form.get_redirect_uri():
                self.success_url = form.get_redirect_uri()

            response = super().form_valid(form)

            # Start loggin success actions (create token, set on cookie...)
            action_context = WiggumActionContext(self.request,
                                                 response,
                                                 actions_context)
            for action in self.get_login_success_actions():
                action_context = action.do(action_context,
                                           self,
                                           user_authenticated)
                if action_context.break_chain:  # no more action chain to process
                    break

            return action_context.response

        # Reset password and username but not the redirect_uri
        form = self.get_form_class()(initial={
            'redirect_uri': form.get_redirect_uri()})
        response = self.render_to_response(self.get_context_data(form=form))

        # Start failure actions
        action_context = WiggumActionContext(self.request,
                                             response,
                                             actions_context)
        for action in self.get_login_failure_actions():
            action_context = action.do(action_context,
                                       self,
                                       user_authenticated)
            if action_context.break_chain:  # no more action chain to process
                break

        # DONT DO THIS AT HOME KIDS!
        # Small and ugly hack for sentry password deletion (ugly... but that's
        # life when you cant do a deep copy of an object easily).
        mutable = self.request.POST._mutable
        self.request.POST._mutable = True
        password = self.request.POST['password']
        self.request.POST['password'] = '************'
        body = getattr(self.request, "_body", b"")
        self.request._body = re.sub("(password=)[^&]*(.*|$)",
                                    "\g<1>************\g<2>",
                                    body.decode("utf-8")).encode()

        logger.warning("User authentication failed",
                       extra={'request': self.request, 'response': response})

        self.request.POST['password'] = password
        self.request.POST._mutable = mutable
        setattr(self.request, "_body", body)
        return action_context.response

    def get_success_url(self):
        uri = get_redirect_url(self.request)

        if not uri:
            return super().get_success_url()
        return uri


    def get_initial(self):
        # Set the return url as a hidden field on the form
        initial = super().get_initial()

        uri = self.get_success_url()
        if uri:
            try:
                URLValidator(uri)
                initial['redirect_uri'] = uri
            except ValidationError:  # If not an url, set default one
                initial['redirect_uri'] = self.success_url
        return initial


class RecoverPasswordView(DynamicTemplateMixin, FormView):
    """Creates the token and sends the email"""

    template_name = 'authorization/recover_password.html'
    form_class = RecoverPasswordForm
    user = None

    # Default  success
    success_url = settings.RECOVER_PASS_REQUEST_SUCCESS_REDIRECT

    # Actions
    recover_actions = settings.RECOVER_PASS_REQUEST_ACTIONS

    def get_recover_actions(self):
        return [str_to_class(action)() for action in self.recover_actions]

    def form_valid(self, form):
        response = super().form_valid(form)
        email = form.cleaned_data['email']
        extra_context = {
            "redirect_uri": form.get_redirect_uri(),
            "form": form,
        }

        # Do recover password actions (send email...)
        action_context = WiggumActionContext(self.request,
                                             response,
                                             extra_context)
        for action in self.get_recover_actions():
            action_context = action.do(action_context, self, email)
            if action_context.break_chain:  # no more action chain to process
                break

        return action_context.response

    def get_initial(self):
        # Set the return url as a hidden field on the form
        initial = super().get_initial()

        uri = get_redirect_url(self.request)
        if uri:
            try:
                URLValidator(uri)
                initial['redirect_uri'] = uri
            except ValidationError:  # If not an url, set default one
                initial['redirect_uri'] = self.success_url
        return initial

class ResetPasswordView(DynamicTemplateMixin, FormView):
    template_name = 'authorization/reset_password.html'
    form_class = ResetPasswordForm

    # Default  success
    success_url = settings.RESET_PASS_SUCCESS_REDIRECT

    reset_pass_actions = settings.RESET_PASS_ACTIONS

    def get_reset_pass_actions(self):
        return [str_to_class(action)() for action in self.reset_pass_actions]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['uuid'] = self.kwargs['uuid']
        context['user_id'] = self.kwargs['user_id']
        return context

    def form_valid(self, form):
        response = super().form_valid(form)

        # Check token and expiration
        try:
            user = User.objects.get(id=self.kwargs['user_id'])
            if str(user.password_reset_token) == self.kwargs['uuid']:
                if user.password_reset_token_expire <= timezone.now():
                    logger.info(
                        "password reset for user {0} token has expire".format(
                            user))
                    msg = _("Token for password reset expired")
                    messages.add_message(self.request, messages.ERROR, msg)
                    return response
                else:  # All ok, reset password
                    # Reset token
                    user.password_reset_token = uuid.uuid4()
                    # Set password
                    user.set_password(form.cleaned_data['password'])
                    # Set user as migrated
                    user.external_service = ""
                    user.save()
                    logger.info(
                        "Password for user {0} has been reset".format(user))
                    msg = _("Password has been reset")
                    messages.add_message(self.request, messages.SUCCESS, msg)

                    # We know that the user access the email(?),

wiggum/themes/templates/clancy/authorization/base.html
{% extends "base.html" %}
{% load pipeline %}

{% block head %}
    {% stylesheet 'login' %}
{% endblock head %}

wiggum/themes/templates/clancy/authorization/login.html
{% extends "clancy/authorization/base.html" %}

{% load i18n %}

{% block content %}
 <div class="container login-container">
    <div class="row">
    <div class="col-md-4 col-md-offset-4">
    <div class="panel panel-primary">
        <div class="panel-heading centered">
        <i class="fa fa-shield fa-5x"></i>

        </div>
        <div class="panel-body">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <span class="label {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} label-danger {% else %} label-success {% endif %}"> {{ message }} </span>
                {% endfor %}
            </ul>
            {% endif %}
            <form class="form-signin" action="{% url 'auth:login'%}" method="post">
                {% csrf_token %}
                <div {% if form.username_or_email.errors %} class="form-group has-error" {% endif %}>

                    {% if form.username_or_email.errors %}
                        {% for error in form.username_or_email.errors %}
                            <span class="label label-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %}

                    <label for="{{ form.username_or_email.id_for_label }}" class="sr-only">{{ form.username_or_email.label }}</label>
                    <input type="text"
                            id="{{ form.username_or_email.id_for_label }}"
                            class="form-control"
                            placeholder="{{ form.username_or_email.label }}"
                            {% if form.username_or_email.value %} value="{{ form.username_or_email.value }}" {% endif %}
                            name="{{ form.username_or_email.name }}"
                            required autofocus >
                </div>
                <div {% if form.password.errors %} class="form-group has-error" {% endif %}>

                    {% if form.password.errors %}
                        {% for error in form.password.errors %}
                            <span class="label label-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                    <label for="{{ form.password.id_for_label }}" class="sr-only">{{ form.password.label }}</label>
                    <input type="password"
                            id="{{ form.password.id_for_label }}"
                            class="form-control"
                            placeholder="{{ form.password.label }}"
                            {% if form.password.value %} value="{{ form.password.value }}" {% endif %}
                            name="{{ form.password.name }}"
                            required>
                </div>
                <input id="{{ form.redirect_uri.id_for_label }}" name="{{ form.redirect_uri.name }}" type="hidden" value="{{ form.redirect_uri.value }}">
                <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Sign in" %} </button>
          </form>
          <div class="forgot-password">
            <a href="{% url "auth:recover-password" %}"> {% trans "Did you forgot your password?" %}</a>
          </div>
        </div>
    </div>
    </div>
  </div>

</div> <!-- /container -->
{% endblock content %}

wiggum/themes/templates/clancy/authorization/recover_password.html
{% extends "clancy/authorization/base.html" %}

{% load i18n %}

{% block content %}
 <div class="container login-container">
    <div class="row">
    <div class="col-md-4 col-md-offset-4">
    <div class="panel panel-primary">
        <div class="panel-heading centered">
        <i class="fa fa-expeditedssl fa-5x"></i>

        </div>
        <div class="panel-body">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <span class="label {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} label-danger {% else %} label-success {% endif %}"> {{ message }} </span>
                {% endfor %}
            </ul>
            {% endif %}

            <form class="form-resetpass" action="{% url 'auth:recover-password'%}" method="post">
                {% csrf_token %}
                <div {% if form.email.errors %} class="form-group has-error" {% endif %}>

                    {% if form.email.errors %}
                        {% for error in form.email.errors %}
                            <span class="label label-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %}

                    <label for="{{ form.email.id_for_label }}" class="sr-only">{{ form.email.label }}</label>
                    <input type="email"
                            id="{{ form.email.id_for_label }}"
                            class="form-control"
                            placeholder="{{ form.email.label }}"
                            {% if form.email.value %} value="{{ form.email.value }}" {% endif %}
                            name="{{ form.email.name }}"
                            required autofocus >
                </div>

                <input id="{{ form.redirect_uri.id_for_label }}" name="{{ form.redirect_uri.name }}" type="hidden" value="{{ form.redirect_uri.value }}">
                <button class="btn btn-lg btn-primary btn-block btn-default" type="submit">{% trans "Recover password" %}</button>
          </form>
        </div>
    </div>
    </div>
  </div>

</div> <!-- /container -->
{% endblock content %}

wiggum/themes/templates/clancy/authorization/reset_password.html
{% extends "clancy/authorization/base.html" %}

{% load i18n %}

{% block content %}
 <div class="container login-container">
    <div class="row">
    <div class="col-md-4 col-md-offset-4">
    <div class="panel panel-primary">
        <div class="panel-heading centered">
        <i class="fa fa-key fa-5x"></i>

        </div>
        <div class="panel-body">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <span class="label {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} label-danger {% else %} label-success {% endif %}"> {{ message }} </span>
                {% endfor %}
            </ul>
            {% endif %}

            <form class="form-resetpass" action="{% url 'auth:reset-password' user_id uuid %}" method="post">
                {% csrf_token %}
                <div {% if form.password.errors %} class="form-group has-error" {% endif %}>

                    {% if form.password.errors %}
                        {% for error in form.password.errors %}
                            <span class="label label-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %}

                    <label for="{{ form.password.id_for_label }}" class="sr-only">{{ form.password.label }}</label>
                    <input type="password"
                            id="{{ form.password.id_for_label }}"
                            class="form-control"
                            placeholder="{{ form.password.label }}"
                            {% if form.password.value %} value="{{ form.password.value }}" {% endif %}
                            name="{{ form.password.name }}"
                            required autofocus >
                </div>
                <div {% if form.password.errors %} class="form-group has-error" {% endif %}>

                    {% if form.password2.errors %}
                        {% for error in form.password2.errors %}
                            <span class="label label-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                    <label for="{{ form.password2.id_for_label }}" class="sr-only">{{ form.password2.label }}</label>
                    <input type="password"
                            id="{{ form.password2.id_for_label }}"
                            class="form-control"
                            placeholder="{{ form.password2.label }}"
                            {% if form.password2.value %} value="{{ form.password2.value }}" {% endif %}
                            name="{{ form.password2.name }}"
                            required>
                </div>
                <input id="{{ form.redirect_uri.id_for_label }}" name="{{ form.redirect_uri.name }}" type="hidden" value="{{ form.redirect_uri.value }}">
                <button class="btn btn-lg btn-primary btn-block btn-default" type="submit">{% trans "reset password" %}</button>
          </form>
        </div>
    </div>
    </div>
  </div>

</div> <!-- /container -->
{% endblock content %}

wiggum/themes/templates/clancy/authorization/test_jwt.html
{% extends "clancy/authorization/base.html" %}
{% load date_filters %}
{% block content %}

<div class="container login-container">

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <span class="label {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} label-danger {% else %} label-success {% endif %}"> {{ message }} </span>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="row">
    {% if jwt %}
      <div class="col-md-10 col-md-offset-1">
      {% if jwt_valid %}
          {% if jwt_payload.impersonate %}
          <div class="panel panel-warning">
            <div class="panel-heading"> <i class="fa fa-warning"></i>CAUTION: Impersonated token (Valid JWT)</div>
          {% else %}
            <div class="panel panel-success">
              <div class="panel-heading"> <i class="fa fa-check"></i> Valid JWT</div>
          {% endif %}
      {% else %}
        <div class="panel panel-danger">
          <div class="panel-heading"> <i class="fa fa-close"></i> Invalid JWT</div>
      {% endif %}
          <div class="panel-body">
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseJWT" aria-expanded="false" aria-controls="collapseJWT">
              Show raw jwt
            </button>
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseDecodedJWT" aria-expanded="false" aria-controls="collapseDecodedJWT">
              Show decoded jwt
            </button>
            <a class="btn btn-danger" href="{% url 'auth:logout' %}" role="button">Logout</a>

            <div class="collapse" id="collapseJWT">
                <pre>{{ jwt }}</pre>
            </div>
            <div class="collapse" id="collapseDecodedJWT">
                <pre>{{ jwt_payload }}</pre>
            </div>
            <table class="table table-striped jwt-table">
              <tr class="info">
                <td >Issuer (iss)</td>
                <td>{{ jwt_payload.iss  }}</td>
              </tr>
              <tr class="info">
                <td>Expiration (exp)</td>
                <td>{{ jwt_payload.exp|epoch_datetime|date:"r"  }}</td>
              </tr>
              <tr class="info">
                <td>Issued at (iat)</td>
                <td>{{ jwt_payload.iat|epoch_datetime|date:"r"  }}</td>
              </tr>
              <tr class="info">
                <td>Not before (nbf)</td>
                <td>{{ jwt_payload.nbf|epoch_datetime|date:"r"  }}</td>
              </tr>
            </table>
            <hr class="gradient">
            <table class="table table-striped jwt-table">
              <tr>
                <td>Id</td>
                <td>{{ jwt_payload.user.id }}</td>
              </tr>
              <tr>
                <td>Email</td>
                <td>{{ jwt_payload.user.email }}</td>
              </tr>
              <tr>
                <td>Username</td>
                <td>{{ jwt_payload.user.username }}</td>
              </tr>
              <tr>
                <td>Name</td>
                <td>{{ jwt_payload.user.first_name }}</td>
              </tr>
              <tr>
                <td>Last name</td>
                <td>{{ jwt_payload.user.last_name }}</td>
              </tr>
              <tr>
                <td>Version</td>
                <td>{{ jwt_payload.version }}</td>
              </tr>
              <tr>
                <td>Impesonated</td>
                <td>{{ jwt_payload.impersonate }}</td>
              </tr>
              <tr>
                <td>Real user id</td>
                <td>{{ jwt_payload.real_user_id }}</td>
              </tr>
              <tr {% if not permissions_set and not jwt_payload.permission %} class="danger" {% endif %}>
                <td>Permissions</td>
                <td>
                  {% if jwt_payload.permission %}
                  <ul>
                    {% for p in jwt_payload.permission %}
                    <li>{{ p }}</li>
                    {% endfor %}
                  </ul>
                  {% else %}
                    Not stored on JWT
                  {% endif %}
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    {% else %}
      <div class="col-md-6 col-md-offset-3">
        <div class="alert alert-warning" role="alert">
          No jwt token. You need to
          <a href="{% url 'auth:login' %}" class="alert-link">login first</a>
        </div>
      </div>
    {% endif %}
  </div>
</div>

{% endblock content %}